### ISSUE TITLE
components folder missing from examples

### ISSUE THREAD

**Issue by mikedizon** [cloudposse/atmos#16]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Getting started guide mentions a components folder in the example file. That folder does not exist. Running `atmos terraform apply eks -s ue2-dev` returns the following error

	* step "terraform workspace": job "terraform workspace": job "terraform shell": job "shell": command "bash -c /usr/bin/terraform-0.13 workspace select ue2-dev || /usr/bin/terraform-0.13 workspace new ue2-dev" in "./components/terraform/eks": chdir ./components/terraform/eks: no such file or directory

## Steps to Reproduce
1. git clone git@github.com:cloudposse/atmos.git
2. cd atmos
3. cd example
4. make all
5. assume-role
6. atmos terraform plan eks --stack=ue2-dev
7.  atmos terraform apply eks --stack=ue2-dev

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment:

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

**Comment by aknysh** [comment]
@mikedizon 
thanks for trying `atmos`.
We did not include the `component` folder because we did not want to maintain those components in this module.
We use https://github.com/vmware-tanzu/carvel-vendir for vendoring components from https://github.com/cloudposse/terraform-aws-components.
There is a vendor config file here https://github.com/cloudposse/atmos/blob/master/example/vendir.yml.

Just run the following commands:

```
make all
cd /localhost/  # this will mount your home directory inside the container
cd <to the atmos repo on your computer>
vendir sync
```

it will download all the files required for the example from https://github.com/cloudposse/terraform-aws-components

**Comment by patlachance** [comment]
based on @aknysh's answer, I guess this issue can be closed no?

**Comment by mikedizon** [comment]
> based on @aknysh's answer, I guess this issue can be closed no?

or the documentation might need to be updated

**Comment by iliazlobin** [comment]
It'd be nice to update [README.md](https://github.com/cloudposse/atmos/blob/master/README.md) as it gets really confusing when you see [the components folder mentioned](https://github.com/cloudposse/atmos/blob/master/README.md#cli-configuration) without much explanation why it's missing in the repo

**Comment by aknysh** [comment]
closing since this is updated (and new functionality added) in the new version of atmos starting with `1.0.0`
